# Publishes a draft snapshot, after performing validation to make sure all
# packages are stable.
name: Validate and Publish Release

on:
  workflow_dispatch:
    inputs:
      release_id:
        description: 'Release id to publish'
        required: true
      package_version:
        description: 'Version of the package'
        required: true
      build_run_id:
        description: 'Run ID for the build_package.yml workflow that triggered this workflow'
        required: true

jobs:
  validate_python_packages:
    name: "Validate python packages"
    # TODO(jennik): Look into testing windows and macos builds.
    runs-on: ubuntu-18.04
    steps:
      - name: Set up python
        id: set_up_python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Download python wheels
        id: download_python_whl
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.WRITE_ACCESS_TOKEN}}
          workflow: build_package.yml
          run_id: ${{ github.event.inputs.build_run_id }}
      - name: Install python packages
        id: install_python_packages
        run: |
          # python -m pip install iree-compiler-snapshot iree-jax-snapshot iree-runtime-snapshot iree-tools-tflite-snapshot iree-tools-tf-snapshot iree-tools-xla-snapshot -f https://github.com/google/iree/tag/snapshot-${{ github.event.inputs.package_version }}
          python -m pip install file://$PWD/artifact/iree-runtime-snapshot

  validate_command_line_tools:
    name: "Validate command line tools"
    runs-on: ubuntu-18.04
    steps:
      - name: Download packages
        id: download_packages
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.WRITE_ACCESS_TOKEN}}
          workflow: build_package.yml
          run_id: ${{ github.event.inputs.build_run_id }}
          name: iree-dist-snapshot-${{ github.event.inputs.package_version }}-linux-x86_64.tar.xz
      - name: Run tools with basic commands
        id: run_tools_with_basic_commands
        run: |
          ./iree-benchmark-module --help
          ./iree-benchmark-trace --help
          ./iree-check-module --help
          # ./iree-dump-module --help
          ./iree-flatcc-cli --help
          ./iree-opt --help
          ./iree-run-mlir --help
          ./iree-run-module --help
          ./iree-run-trace --help
          ./iree-tblgen --help
          ./iree-translate --help

  publish_release:
    name: "Publish release"
    needs: [validate_python_packages, validate_command_line_tools]
    runs-on: ubuntu-18.04
    steps:
      - name: Publish Release
        id: publish_release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_ACCESS_TOKEN }}
        with:
          release_id: ${{ github.event.inputs.release_id }}
